# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jhzhou/working/nbiot_sdk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jhzhou/working/nbiot_sdk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jhzhou/working/nbiot_sdk/CMakeFiles /home/jhzhou/working/nbiot_sdk/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jhzhou/working/nbiot_sdk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nbiot_sdk

# Build rule for target.
nbiot_sdk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nbiot_sdk
.PHONY : nbiot_sdk

# fast build rule for target.
nbiot_sdk/fast:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/build
.PHONY : nbiot_sdk/fast

#=============================================================================
# Target rules for targets named nbiot_sample

# Build rule for target.
nbiot_sample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nbiot_sample
.PHONY : nbiot_sample

# fast build rule for target.
nbiot_sample/fast:
	$(MAKE) -f sample/CMakeFiles/nbiot_sample.dir/build.make sample/CMakeFiles/nbiot_sample.dir/build
.PHONY : nbiot_sample/fast

platforms/posix/environment.o: platforms/posix/environment.c.o
.PHONY : platforms/posix/environment.o

# target to build an object file
platforms/posix/environment.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/platforms/posix/environment.c.o
.PHONY : platforms/posix/environment.c.o

platforms/posix/environment.i: platforms/posix/environment.c.i
.PHONY : platforms/posix/environment.i

# target to preprocess a source file
platforms/posix/environment.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/platforms/posix/environment.c.i
.PHONY : platforms/posix/environment.c.i

platforms/posix/environment.s: platforms/posix/environment.c.s
.PHONY : platforms/posix/environment.s

# target to generate assembly for a file
platforms/posix/environment.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/platforms/posix/environment.c.s
.PHONY : platforms/posix/environment.c.s

platforms/posix/memory.o: platforms/posix/memory.c.o
.PHONY : platforms/posix/memory.o

# target to build an object file
platforms/posix/memory.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/platforms/posix/memory.c.o
.PHONY : platforms/posix/memory.c.o

platforms/posix/memory.i: platforms/posix/memory.c.i
.PHONY : platforms/posix/memory.i

# target to preprocess a source file
platforms/posix/memory.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/platforms/posix/memory.c.i
.PHONY : platforms/posix/memory.c.i

platforms/posix/memory.s: platforms/posix/memory.c.s
.PHONY : platforms/posix/memory.s

# target to generate assembly for a file
platforms/posix/memory.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/platforms/posix/memory.c.s
.PHONY : platforms/posix/memory.c.s

platforms/posix/socket.o: platforms/posix/socket.c.o
.PHONY : platforms/posix/socket.o

# target to build an object file
platforms/posix/socket.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/platforms/posix/socket.c.o
.PHONY : platforms/posix/socket.c.o

platforms/posix/socket.i: platforms/posix/socket.c.i
.PHONY : platforms/posix/socket.i

# target to preprocess a source file
platforms/posix/socket.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/platforms/posix/socket.c.i
.PHONY : platforms/posix/socket.c.i

platforms/posix/socket.s: platforms/posix/socket.c.s
.PHONY : platforms/posix/socket.s

# target to generate assembly for a file
platforms/posix/socket.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/platforms/posix/socket.c.s
.PHONY : platforms/posix/socket.c.s

platforms/posix/time.o: platforms/posix/time.c.o
.PHONY : platforms/posix/time.o

# target to build an object file
platforms/posix/time.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/platforms/posix/time.c.o
.PHONY : platforms/posix/time.c.o

platforms/posix/time.i: platforms/posix/time.c.i
.PHONY : platforms/posix/time.i

# target to preprocess a source file
platforms/posix/time.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/platforms/posix/time.c.i
.PHONY : platforms/posix/time.c.i

platforms/posix/time.s: platforms/posix/time.c.s
.PHONY : platforms/posix/time.s

# target to generate assembly for a file
platforms/posix/time.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/platforms/posix/time.c.s
.PHONY : platforms/posix/time.c.s

platforms/posix/utils.o: platforms/posix/utils.c.o
.PHONY : platforms/posix/utils.o

# target to build an object file
platforms/posix/utils.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/platforms/posix/utils.c.o
.PHONY : platforms/posix/utils.c.o

platforms/posix/utils.i: platforms/posix/utils.c.i
.PHONY : platforms/posix/utils.i

# target to preprocess a source file
platforms/posix/utils.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/platforms/posix/utils.c.i
.PHONY : platforms/posix/utils.c.i

platforms/posix/utils.s: platforms/posix/utils.c.s
.PHONY : platforms/posix/utils.s

# target to generate assembly for a file
platforms/posix/utils.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/platforms/posix/utils.c.s
.PHONY : platforms/posix/utils.c.s

source/lwm2m/block.o: source/lwm2m/block.c.o
.PHONY : source/lwm2m/block.o

# target to build an object file
source/lwm2m/block.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/block.c.o
.PHONY : source/lwm2m/block.c.o

source/lwm2m/block.i: source/lwm2m/block.c.i
.PHONY : source/lwm2m/block.i

# target to preprocess a source file
source/lwm2m/block.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/block.c.i
.PHONY : source/lwm2m/block.c.i

source/lwm2m/block.s: source/lwm2m/block.c.s
.PHONY : source/lwm2m/block.s

# target to generate assembly for a file
source/lwm2m/block.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/block.c.s
.PHONY : source/lwm2m/block.c.s

source/lwm2m/bootstrap.o: source/lwm2m/bootstrap.c.o
.PHONY : source/lwm2m/bootstrap.o

# target to build an object file
source/lwm2m/bootstrap.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/bootstrap.c.o
.PHONY : source/lwm2m/bootstrap.c.o

source/lwm2m/bootstrap.i: source/lwm2m/bootstrap.c.i
.PHONY : source/lwm2m/bootstrap.i

# target to preprocess a source file
source/lwm2m/bootstrap.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/bootstrap.c.i
.PHONY : source/lwm2m/bootstrap.c.i

source/lwm2m/bootstrap.s: source/lwm2m/bootstrap.c.s
.PHONY : source/lwm2m/bootstrap.s

# target to generate assembly for a file
source/lwm2m/bootstrap.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/bootstrap.c.s
.PHONY : source/lwm2m/bootstrap.c.s

source/lwm2m/coap.o: source/lwm2m/coap.c.o
.PHONY : source/lwm2m/coap.o

# target to build an object file
source/lwm2m/coap.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/coap.c.o
.PHONY : source/lwm2m/coap.c.o

source/lwm2m/coap.i: source/lwm2m/coap.c.i
.PHONY : source/lwm2m/coap.i

# target to preprocess a source file
source/lwm2m/coap.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/coap.c.i
.PHONY : source/lwm2m/coap.c.i

source/lwm2m/coap.s: source/lwm2m/coap.c.s
.PHONY : source/lwm2m/coap.s

# target to generate assembly for a file
source/lwm2m/coap.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/coap.c.s
.PHONY : source/lwm2m/coap.c.s

source/lwm2m/data.o: source/lwm2m/data.c.o
.PHONY : source/lwm2m/data.o

# target to build an object file
source/lwm2m/data.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/data.c.o
.PHONY : source/lwm2m/data.c.o

source/lwm2m/data.i: source/lwm2m/data.c.i
.PHONY : source/lwm2m/data.i

# target to preprocess a source file
source/lwm2m/data.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/data.c.i
.PHONY : source/lwm2m/data.c.i

source/lwm2m/data.s: source/lwm2m/data.c.s
.PHONY : source/lwm2m/data.s

# target to generate assembly for a file
source/lwm2m/data.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/data.c.s
.PHONY : source/lwm2m/data.c.s

source/lwm2m/discover.o: source/lwm2m/discover.c.o
.PHONY : source/lwm2m/discover.o

# target to build an object file
source/lwm2m/discover.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/discover.c.o
.PHONY : source/lwm2m/discover.c.o

source/lwm2m/discover.i: source/lwm2m/discover.c.i
.PHONY : source/lwm2m/discover.i

# target to preprocess a source file
source/lwm2m/discover.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/discover.c.i
.PHONY : source/lwm2m/discover.c.i

source/lwm2m/discover.s: source/lwm2m/discover.c.s
.PHONY : source/lwm2m/discover.s

# target to generate assembly for a file
source/lwm2m/discover.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/discover.c.s
.PHONY : source/lwm2m/discover.c.s

source/lwm2m/list.o: source/lwm2m/list.c.o
.PHONY : source/lwm2m/list.o

# target to build an object file
source/lwm2m/list.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/list.c.o
.PHONY : source/lwm2m/list.c.o

source/lwm2m/list.i: source/lwm2m/list.c.i
.PHONY : source/lwm2m/list.i

# target to preprocess a source file
source/lwm2m/list.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/list.c.i
.PHONY : source/lwm2m/list.c.i

source/lwm2m/list.s: source/lwm2m/list.c.s
.PHONY : source/lwm2m/list.s

# target to generate assembly for a file
source/lwm2m/list.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/list.c.s
.PHONY : source/lwm2m/list.c.s

source/lwm2m/lwm2m.o: source/lwm2m/lwm2m.c.o
.PHONY : source/lwm2m/lwm2m.o

# target to build an object file
source/lwm2m/lwm2m.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/lwm2m.c.o
.PHONY : source/lwm2m/lwm2m.c.o

source/lwm2m/lwm2m.i: source/lwm2m/lwm2m.c.i
.PHONY : source/lwm2m/lwm2m.i

# target to preprocess a source file
source/lwm2m/lwm2m.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/lwm2m.c.i
.PHONY : source/lwm2m/lwm2m.c.i

source/lwm2m/lwm2m.s: source/lwm2m/lwm2m.c.s
.PHONY : source/lwm2m/lwm2m.s

# target to generate assembly for a file
source/lwm2m/lwm2m.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/lwm2m.c.s
.PHONY : source/lwm2m/lwm2m.c.s

source/lwm2m/management.o: source/lwm2m/management.c.o
.PHONY : source/lwm2m/management.o

# target to build an object file
source/lwm2m/management.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/management.c.o
.PHONY : source/lwm2m/management.c.o

source/lwm2m/management.i: source/lwm2m/management.c.i
.PHONY : source/lwm2m/management.i

# target to preprocess a source file
source/lwm2m/management.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/management.c.i
.PHONY : source/lwm2m/management.c.i

source/lwm2m/management.s: source/lwm2m/management.c.s
.PHONY : source/lwm2m/management.s

# target to generate assembly for a file
source/lwm2m/management.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/management.c.s
.PHONY : source/lwm2m/management.c.s

source/lwm2m/objects.o: source/lwm2m/objects.c.o
.PHONY : source/lwm2m/objects.o

# target to build an object file
source/lwm2m/objects.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/objects.c.o
.PHONY : source/lwm2m/objects.c.o

source/lwm2m/objects.i: source/lwm2m/objects.c.i
.PHONY : source/lwm2m/objects.i

# target to preprocess a source file
source/lwm2m/objects.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/objects.c.i
.PHONY : source/lwm2m/objects.c.i

source/lwm2m/objects.s: source/lwm2m/objects.c.s
.PHONY : source/lwm2m/objects.s

# target to generate assembly for a file
source/lwm2m/objects.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/objects.c.s
.PHONY : source/lwm2m/objects.c.s

source/lwm2m/observe.o: source/lwm2m/observe.c.o
.PHONY : source/lwm2m/observe.o

# target to build an object file
source/lwm2m/observe.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/observe.c.o
.PHONY : source/lwm2m/observe.c.o

source/lwm2m/observe.i: source/lwm2m/observe.c.i
.PHONY : source/lwm2m/observe.i

# target to preprocess a source file
source/lwm2m/observe.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/observe.c.i
.PHONY : source/lwm2m/observe.c.i

source/lwm2m/observe.s: source/lwm2m/observe.c.s
.PHONY : source/lwm2m/observe.s

# target to generate assembly for a file
source/lwm2m/observe.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/observe.c.s
.PHONY : source/lwm2m/observe.c.s

source/lwm2m/packet.o: source/lwm2m/packet.c.o
.PHONY : source/lwm2m/packet.o

# target to build an object file
source/lwm2m/packet.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/packet.c.o
.PHONY : source/lwm2m/packet.c.o

source/lwm2m/packet.i: source/lwm2m/packet.c.i
.PHONY : source/lwm2m/packet.i

# target to preprocess a source file
source/lwm2m/packet.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/packet.c.i
.PHONY : source/lwm2m/packet.c.i

source/lwm2m/packet.s: source/lwm2m/packet.c.s
.PHONY : source/lwm2m/packet.s

# target to generate assembly for a file
source/lwm2m/packet.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/packet.c.s
.PHONY : source/lwm2m/packet.c.s

source/lwm2m/registration.o: source/lwm2m/registration.c.o
.PHONY : source/lwm2m/registration.o

# target to build an object file
source/lwm2m/registration.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/registration.c.o
.PHONY : source/lwm2m/registration.c.o

source/lwm2m/registration.i: source/lwm2m/registration.c.i
.PHONY : source/lwm2m/registration.i

# target to preprocess a source file
source/lwm2m/registration.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/registration.c.i
.PHONY : source/lwm2m/registration.c.i

source/lwm2m/registration.s: source/lwm2m/registration.c.s
.PHONY : source/lwm2m/registration.s

# target to generate assembly for a file
source/lwm2m/registration.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/registration.c.s
.PHONY : source/lwm2m/registration.c.s

source/lwm2m/tlv.o: source/lwm2m/tlv.c.o
.PHONY : source/lwm2m/tlv.o

# target to build an object file
source/lwm2m/tlv.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/tlv.c.o
.PHONY : source/lwm2m/tlv.c.o

source/lwm2m/tlv.i: source/lwm2m/tlv.c.i
.PHONY : source/lwm2m/tlv.i

# target to preprocess a source file
source/lwm2m/tlv.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/tlv.c.i
.PHONY : source/lwm2m/tlv.c.i

source/lwm2m/tlv.s: source/lwm2m/tlv.c.s
.PHONY : source/lwm2m/tlv.s

# target to generate assembly for a file
source/lwm2m/tlv.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/tlv.c.s
.PHONY : source/lwm2m/tlv.c.s

source/lwm2m/transaction.o: source/lwm2m/transaction.c.o
.PHONY : source/lwm2m/transaction.o

# target to build an object file
source/lwm2m/transaction.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/transaction.c.o
.PHONY : source/lwm2m/transaction.c.o

source/lwm2m/transaction.i: source/lwm2m/transaction.c.i
.PHONY : source/lwm2m/transaction.i

# target to preprocess a source file
source/lwm2m/transaction.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/transaction.c.i
.PHONY : source/lwm2m/transaction.c.i

source/lwm2m/transaction.s: source/lwm2m/transaction.c.s
.PHONY : source/lwm2m/transaction.s

# target to generate assembly for a file
source/lwm2m/transaction.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/transaction.c.s
.PHONY : source/lwm2m/transaction.c.s

source/lwm2m/uri.o: source/lwm2m/uri.c.o
.PHONY : source/lwm2m/uri.o

# target to build an object file
source/lwm2m/uri.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/uri.c.o
.PHONY : source/lwm2m/uri.c.o

source/lwm2m/uri.i: source/lwm2m/uri.c.i
.PHONY : source/lwm2m/uri.i

# target to preprocess a source file
source/lwm2m/uri.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/uri.c.i
.PHONY : source/lwm2m/uri.c.i

source/lwm2m/uri.s: source/lwm2m/uri.c.s
.PHONY : source/lwm2m/uri.s

# target to generate assembly for a file
source/lwm2m/uri.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/uri.c.s
.PHONY : source/lwm2m/uri.c.s

source/lwm2m/utils.o: source/lwm2m/utils.c.o
.PHONY : source/lwm2m/utils.o

# target to build an object file
source/lwm2m/utils.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/utils.c.o
.PHONY : source/lwm2m/utils.c.o

source/lwm2m/utils.i: source/lwm2m/utils.c.i
.PHONY : source/lwm2m/utils.i

# target to preprocess a source file
source/lwm2m/utils.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/utils.c.i
.PHONY : source/lwm2m/utils.c.i

source/lwm2m/utils.s: source/lwm2m/utils.c.s
.PHONY : source/lwm2m/utils.s

# target to generate assembly for a file
source/lwm2m/utils.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/lwm2m/utils.c.s
.PHONY : source/lwm2m/utils.c.s

source/m2m.o: source/m2m.c.o
.PHONY : source/m2m.o

# target to build an object file
source/m2m.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/m2m.c.o
.PHONY : source/m2m.c.o

source/m2m.i: source/m2m.c.i
.PHONY : source/m2m.i

# target to preprocess a source file
source/m2m.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/m2m.c.i
.PHONY : source/m2m.c.i

source/m2m.s: source/m2m.c.s
.PHONY : source/m2m.s

# target to generate assembly for a file
source/m2m.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/m2m.c.s
.PHONY : source/m2m.c.s

source/nbiot.o: source/nbiot.c.o
.PHONY : source/nbiot.o

# target to build an object file
source/nbiot.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/nbiot.c.o
.PHONY : source/nbiot.c.o

source/nbiot.i: source/nbiot.c.i
.PHONY : source/nbiot.i

# target to preprocess a source file
source/nbiot.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/nbiot.c.i
.PHONY : source/nbiot.c.i

source/nbiot.s: source/nbiot.c.s
.PHONY : source/nbiot.s

# target to generate assembly for a file
source/nbiot.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/nbiot.c.s
.PHONY : source/nbiot.c.s

source/resource.o: source/resource.c.o
.PHONY : source/resource.o

# target to build an object file
source/resource.c.o:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/resource.c.o
.PHONY : source/resource.c.o

source/resource.i: source/resource.c.i
.PHONY : source/resource.i

# target to preprocess a source file
source/resource.c.i:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/resource.c.i
.PHONY : source/resource.c.i

source/resource.s: source/resource.c.s
.PHONY : source/resource.s

# target to generate assembly for a file
source/resource.c.s:
	$(MAKE) -f CMakeFiles/nbiot_sdk.dir/build.make CMakeFiles/nbiot_sdk.dir/source/resource.c.s
.PHONY : source/resource.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... nbiot_sdk"
	@echo "... rebuild_cache"
	@echo "... nbiot_sample"
	@echo "... platforms/posix/environment.o"
	@echo "... platforms/posix/environment.i"
	@echo "... platforms/posix/environment.s"
	@echo "... platforms/posix/memory.o"
	@echo "... platforms/posix/memory.i"
	@echo "... platforms/posix/memory.s"
	@echo "... platforms/posix/socket.o"
	@echo "... platforms/posix/socket.i"
	@echo "... platforms/posix/socket.s"
	@echo "... platforms/posix/time.o"
	@echo "... platforms/posix/time.i"
	@echo "... platforms/posix/time.s"
	@echo "... platforms/posix/utils.o"
	@echo "... platforms/posix/utils.i"
	@echo "... platforms/posix/utils.s"
	@echo "... source/lwm2m/block.o"
	@echo "... source/lwm2m/block.i"
	@echo "... source/lwm2m/block.s"
	@echo "... source/lwm2m/bootstrap.o"
	@echo "... source/lwm2m/bootstrap.i"
	@echo "... source/lwm2m/bootstrap.s"
	@echo "... source/lwm2m/coap.o"
	@echo "... source/lwm2m/coap.i"
	@echo "... source/lwm2m/coap.s"
	@echo "... source/lwm2m/data.o"
	@echo "... source/lwm2m/data.i"
	@echo "... source/lwm2m/data.s"
	@echo "... source/lwm2m/discover.o"
	@echo "... source/lwm2m/discover.i"
	@echo "... source/lwm2m/discover.s"
	@echo "... source/lwm2m/list.o"
	@echo "... source/lwm2m/list.i"
	@echo "... source/lwm2m/list.s"
	@echo "... source/lwm2m/lwm2m.o"
	@echo "... source/lwm2m/lwm2m.i"
	@echo "... source/lwm2m/lwm2m.s"
	@echo "... source/lwm2m/management.o"
	@echo "... source/lwm2m/management.i"
	@echo "... source/lwm2m/management.s"
	@echo "... source/lwm2m/objects.o"
	@echo "... source/lwm2m/objects.i"
	@echo "... source/lwm2m/objects.s"
	@echo "... source/lwm2m/observe.o"
	@echo "... source/lwm2m/observe.i"
	@echo "... source/lwm2m/observe.s"
	@echo "... source/lwm2m/packet.o"
	@echo "... source/lwm2m/packet.i"
	@echo "... source/lwm2m/packet.s"
	@echo "... source/lwm2m/registration.o"
	@echo "... source/lwm2m/registration.i"
	@echo "... source/lwm2m/registration.s"
	@echo "... source/lwm2m/tlv.o"
	@echo "... source/lwm2m/tlv.i"
	@echo "... source/lwm2m/tlv.s"
	@echo "... source/lwm2m/transaction.o"
	@echo "... source/lwm2m/transaction.i"
	@echo "... source/lwm2m/transaction.s"
	@echo "... source/lwm2m/uri.o"
	@echo "... source/lwm2m/uri.i"
	@echo "... source/lwm2m/uri.s"
	@echo "... source/lwm2m/utils.o"
	@echo "... source/lwm2m/utils.i"
	@echo "... source/lwm2m/utils.s"
	@echo "... source/m2m.o"
	@echo "... source/m2m.i"
	@echo "... source/m2m.s"
	@echo "... source/nbiot.o"
	@echo "... source/nbiot.i"
	@echo "... source/nbiot.s"
	@echo "... source/resource.o"
	@echo "... source/resource.i"
	@echo "... source/resource.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

